checks:
    php: true
filter: {  }
coding_style:
    php:
        indentation:
            general:
                use_tabs: true
        spaces:
            around_operators:
                concatenation: false
build:
    tests:
        override:
            -
                command: 'phpunit --coverage-clover=Tests/coverage.xml'
                coverage:
                    file: 'some-file'
                    format: 'php-clover'